<!-- SQL문을 작성하기 전에 정상작동 하는지 확인하는 페이지 -->
<!-- STORE(맛집) 데이터 베이스 -->
SELECT * FROM STORE;            <!-- 테이블 안의 데이터 모두 출력 -->

DROP TABLE STORE;               <!-- 테이블 삭제 -->

DELETE FROM STORE WHERE id = 2; <!-- 테이블안의 2번째 행 삭제 -->

ALTER TABLE STORE
    ADD (tag varchar(30));          <!-- 테이블에 새로운 열 추가-->

CREATE TABLE STORE              <!-- 새로운 테이블 생성 -->
(
    storeid NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    storename VARCHAR2(10),
    storlocation VARCHAR2(30),
    stormenu VARCHAR2(10),
    storprice VARCHAR2(10),
    stortag VARCHAR2(30),
    storefilename VARCHAR2(250),
    storefilepath VARCHAR2(250),
    PRIMARY KEY (id)

    );


alter table store add storefilename varchar2(250);      // 열 추가

alter table store drop column storefilename;        // 열 삭제