<!-- SQL문을 작성하기 전에 정상작동 하는지 확인하는 페이지 -->
<!-- STORE(맛집) 데이터 베이스 -->
SELECT * FROM STORE;            <!-- 테이블 안의 데이터 모두 출력 -->

DROP TABLE STORE;               <!-- 테이블 삭제 -->

DELETE FROM STORE WHERE id = 2; <!-- 테이블안의 2번째 행 삭제 -->

ALTER TABLE STORE
    ADD (tag varchar(30));          <!-- 테이블에 새로운 열 추가-->

alter table store add storefilename varchar2(250);      <!-- 열 추가 -->

alter table store drop column storefilename;        <!-- 열 삭제 -->


CREATE TABLE STORE              <!-- 맛집 테이블 생성 -->
(
    storeid NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    storename VARCHAR2(10),
    storelocation VARCHAR2(30),
    storemenu VARCHAR2(10),
    storeprice VARCHAR2(10),
    storetag VARCHAR2(30),
    storefilename VARCHAR2(250),
    storefilepath VARCHAR2(250),
    storedate DATE,
    PRIMARY KEY (storeid)

    );


CREATE TABLE PLACE              <!-- 가볼만한 곳 테이블 생성 -->
(
    placeid NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    placelocation VARCHAR2(30),
    placename VARCHAR2(20),
    placedate VARCHAR2(30),
    placeweather VARCHAR2(20),
    placescore VARCHAR2(20),
    placememo text,
    placetag VARCHAR2(20),
    placefilename VARCHAR2(250),
    placefilepath VARCHAR2(250),
    storedate DATE,
    PRIMARY KEY (placeid)

    );

CREATE TABLE LODGING              <!-- 숙소 테이블 생성 -->
(
    lodgingid NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    lodgingname VARCHAR2(20),
    lodginglocation VARCHAR2(30),
    lodgingprice int,
    lodgingscore VARCHAR2(20),
    lodgingmemo text,
    lodgingtag VARCHAR2(20),
    lodgingfilename VARCHAR2(250),
    lodgingfilepath VARCHAR2(250),
    storedate DATE,
    PRIMARY KEY (lodgingid)

    );